# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - jif1
    - jif2
    - jif3
    - jif4
    - jmf1
    - jmf2
    - jmf3
    - jmf4
    - jpf1
    - jpf2
    - jpf3
    - jpf4
    - jth1
    - jth2
    - jth3
    - jth4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: allegro_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - jif1
      - jif2
      - jif3
      - jif4
      - jmf1
      - jmf2
      - jmf3
      - jmf4
      - jpf1
      - jpf2
      - jpf3
      - jpf4
      - jth1
      - jth2
      - jth3
      - jth4